const FETCH_COCKTAIL_REQUEST = "cocktail/FETCH_REQUEST";
const FETCH_COCKTAIL_SUCCESS = "cocktail/FETCH_SUCCESS";
const FETCH_COCKTAIL_FAILURE = "cocktail/FETCH_FAILURE";

const UPDATE_INGREDIENT = "cocktail/UPDATE_INGREDIENT";
const UPDATE_MEASURE = "cocktail/UPDATE_MEASURE";

export {
  FETCH_COCKTAIL_REQUEST,
  FETCH_COCKTAIL_SUCCESS,
  FETCH_COCKTAIL_FAILURE,
  UPDATE_INGREDIENT,
  UPDATE_MEASURE,
};
